fix: OAuth controls
nrkno/sofie-core pull request #826
Opened 2022-12-20 12:07 UTC by imaretic

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Updates the UI for controlling the Spreadsheet-Gateway and its credentials.

* **What is the current behavior?** (You can also link to an open issue here)
Currently, it works, but the CSS needs some updating, to improve UX.

* **What is the new behavior (if this is a feature change)?**
With this change, there are now two options: to reset app credentials or to reset user credentials, depending on what the user wants to perform. The overall style is also updated so it's all aligned well.

* **Other information**:

**Status**

- [ ] Code documentation for the relevant parts in the code has been added/updated by the PR author
- [-] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

2023-01-02 14:20 UTC, jstarpl requested changes

2023-01-02 14:20 UTC, jstarpl commented on meteor/client/ui/Settings/components/ConfigManifestOAuthFlow.tsx
> +								style={{ marginRight: '10px' }}
Could this be changed to a utility class instead? I think `mrs` utility class has the same effect.

2023-01-02 14:20 UTC, jstarpl commented on meteor/client/ui/Settings/components/ConfigManifestOAuthFlow.tsx
> +													<button className="btn btn-primary">{t('Authorize App Access')}</button>
A `button` in an `<a href>` doesn't seem right. I think this should work OK with just having an `<a className='btn'>`. If not - `window.open`?

2023-01-04 11:54 UTC, imaretic commented
In the new commit:
- CSS styling has been replaced with the utility class
- Button is not inside `<a>` anymore - of course
- Resetting app credentials won't kill the spreadsheet gateway anymore
- Resetting user credentials will only delete user credentials and not app credentials

2023-01-04 12:11 UTC, imaretic commented
In the new commit:

- CSS styling has been replaced with the utility class
- Button is not inside `<a>` anymore - of course
- Resetting app credentials won't kill the spreadsheet gateway anymore
- Resetting user credentials will only delete user credentials and not app credentials

2023-01-11 08:58 UTC, jstarpl approved these changes

2023-01-11 09:00 UTC, merged